### ISSUE TITLE
conf 文件

### ISSUE THREAD

**Issue by yanzhengbin** [yanzhengbin/Neural_Style_Transform#16]
conf文件里的内容的作用是干什么？

**Comment by haiyang007** [comment]
conf 文件里边包含了具体的训练时的超参数的设置。
他包含了：1. 风格图片 2.内容和风格损失的超参数 3.风格图片的高宽 4. 训练时的epoch 5.内容和风格损失用VGG中哪几个网络层 6. 模型文件的命名和保存地址
训练的时候可以通过调整conf文件夹的文件内容，改变超参数，训练出不错的模型文件。
